function createfigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 08-Mar-2013 12:57:15

% Create figure
figure1 = figure('PaperType','A4',...
    'PaperSize',[20.98404194812 29.67743169791],...
    'PaperUnits','centimeters');

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.994393595107138 1.91711440039075]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-1.83509455900959 92.3716699155296]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1,'Color',[1 0 0],'DisplayName','3)0p3A_input_8dBm_av');

% Create xlabel
xlabel('Time (ns)');

% Create ylabel
ylabel('Signal input in waveguide (mW)');

% Create arrow
annotation(figure1,'arrow',[0.348214285714286 0.414285714285714],...
    [0.513285714285714 0.511904761904762]);

% Create arrow
annotation(figure1,'arrow',[0.535714285714286 0.466071428571429],...
    [0.511904761904762 0.511904761904762]);

% Create textbox
annotation(figure1,'textbox',...
    [0.502475247524752 0.458081064920481 0.0296495956873315 0.02997002997003],...
    'String',{'45 ps'},...
    'LineStyle','none');

